### ISSUE TITLE
Cannot find module './lib'

### ISSUE THREAD

**Issue by VagrantPi** [lxzxl/koa-i18next-middleware#6]
in index.js:
```
module.exports = require('./lib');
```

but in your  project can't find this folder

this's my npm log:

```
> node index.js

module.js:472
    throw err;
    ^

Error: Cannot find module './lib'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/TrunkStudioWS/node_modules/koa-i18next-middleware/index.js:1:80)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by lxzxl** [comment]
@VagrantPi Sorry, that file is not working. The entry is `register.js`. You can debugging by running `npm run debug`.
